### ISSUE TITLE
Working examples link broken

### ISSUE THREAD

**Issue by joaosantos15** [Zondax/filecoin-solidity#114]
Hello :) I was going through the docs and noticed that the working examples link (https://docs.zondax.ch/fevm/filecoin-solidity-api/contracts/v0.8/testContracts) on the [How to use it in my project](https://docs.zondax.ch/fevm/filecoin-solidity-api/api/use-it#working-examples) page is broken.

Is there some other place where we can find working examples? Thank you

**Comment by ainhoa-a** [comment]
Thank you @joaosantos15  we will correct this asap.

**Comment by emmanuelm41** [comment]
Thanks @joaosantos15. It is fixed now!

**Comment by joaosantos15** [comment]
Thank you, this was great :) 
Btw, do you have any working examples for using the Hyperspace testnet? Someone told me that the library was working (i.e. not mocked) for that network.

**Comment by ainhoa-a** [comment]
Hi @joaosantos15  Hyperspace is not available yet, it is planned to be released mid January and we plan to offer support for it as soon as it is released. Stay tuned!
