### ISSUE TITLE
exit 33

### ISSUE THREAD

**Issue by phantom-rabbit** [Zondax/filecoin-solidity#136]
```
pragma solidity ^0.8.0;

import "@zondax/filecoin-solidity/contracts/v0.8/MinerAPI.sol";
import { MinerTypes } from "@zondax/filecoin-solidity/contracts/v0.8/types/MinerTypes.sol";

contract Miner {
    function getBeneficiary() external returns (MinerTypes.GetBeneficiaryReturn memory) {
        bytes memory addr = bytes("0xff00000000000000000000000000000000000414");
        MinerTypes.GetBeneficiaryReturn memory response = MinerAPI.getBeneficiary(addr);
        return response;
    }
}
```

I returned some errors when executing the call!

<img width="492" alt="image" src="https://user-images.githubusercontent.com/49083897/211179659-161db675-e320-4b2f-82cb-ab2e5162cea1.png">

<img width="326" alt="image" src="https://user-images.githubusercontent.com/49083897/211179667-04ed4a90-2de1-4eab-9ee7-826371becae5.png">

:link: [zboto Link](https://app.clickup.com/t/86772ybcq)

**Comment by phantom-rabbit** [comment]
https://wallaby.filscan.io/tipset/message-detail?cid=bafy2bzacedhkumgmmus2ydz57en3tegf3hqkkv6jfweagkipxxpfcwtwjy4mi

**Comment by rllola** [comment]
The address doesn't look right to me... where did you get this value ?

**Comment by emmanuelm41** [comment]
@phantom-rabbit as Lola wrote before, the address should be from a valid miner. 

Is this one a miner address?
'0xff00000000000000000000000000000000000414`

**Comment by phantom-rabbit** [comment]
```
pragma solidity ^0.8.0;

import "@zondax/filecoin-solidity/contracts/v0.8/MinerAPI.sol";
import { MinerTypes } from "@zondax/filecoin-solidity/contracts/v0.8/types/MinerTypes.sol";

contract LoansContract {

    function getBeneficiary() external returns (MinerTypes.GetBeneficiaryReturn memory) {
        bytes memory addr = bytes("0xff000000000000000000000000000000000003e9");
        MinerTypes.GetBeneficiaryReturn memory response = MinerAPI.getBeneficiary(addr);
        return response;
    }

}

```

I changed the address, which is the same error. This is the address of t01001

**Comment by phantom-rabbit** [comment]
![image](https://user-images.githubusercontent.com/49083897/211974896-f86aece5-24fa-4da0-896a-d95fc59f956b.png)

**Comment by rllola** [comment]
@phantom-rabbit Your address is not correct. If the miner address is `t01001` then you address should be 
`0x0003e9`.

Try this
```
pragma solidity ^0.8.0;

import "@zondax/filecoin-solidity/contracts/v0.8/MinerAPI.sol";
import { MinerTypes } from "@zondax/filecoin-solidity/contracts/v0.8/types/MinerTypes.sol";

contract LoansContract {

    function getBeneficiary() external returns (MinerTypes.GetBeneficiaryReturn memory) {
        bytes memory addr = bytes("0x0003e9");
        MinerTypes.GetBeneficiaryReturn memory response = MinerAPI.getBeneficiary(addr);
        return response;
    }

}
```

**Comment by emmanuelm41** [comment]
@phantom-rabbit try what Lola mentioned. This address `t01001` is filecoin ID type. What you used is the ethereal version for the Filecoin EVM of that address. However, Filecoin libraries expect the filecoin addresses.

**Comment by emmanuelm41** [comment]
@phantom-rabbit I leave you here more info about addresses. What you need to pass is the bytes representation of a filecoin address. 
https://spec.filecoin.io/appendix/address/

**Comment by emmanuelm41** [comment]
@phantom-rabbit any comments on this? I will soon close the issue otherwise. Thanks!!

**Comment by phantom-rabbit** [comment]
Thank you for your positive reply. I am busy with other things at this time. Sorry for not responding in time, I will try again. Thank you.

**Comment by phantom-rabbit** [comment]
<img width="687" alt="image" src="https://user-images.githubusercontent.com/49083897/215417336-a54df0b6-169c-4917-b1f8-e573ae330ba7.png">
I tried to call the above contract, but an error still occurred

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/49083897/215417562-4d87197e-db98-4598-be98-119b7e2381f7.png">

**Comment by phantom-rabbit** [comment]
in heperspace https://hyperspace.filfox.info/en/message/bafy2bzacedhcz2dcr3uri2wqlpdb4lextel3mzu4cujxwi4dv7lyqhrexzsrm

**Comment by phantom-rabbit** [comment]
@emmanuelm41  Please help me check

**Comment by emmanuelm41** [comment]
@phantom-rabbit Use this tool to convert from string to bytes representation, and use that bytes representation as argument 
https://github.com/Zondax/filecoin-signing-tools/blob/7c7970e2f45d4f4e01362176188ffe906bf897a7/signer-npm/js/src/index.ts#L40-L42

**Comment by phantom-rabbit** [comment]
Sorry, I still can't execute

**Comment by emmanuelm41** [comment]
Could you share the new value you used? and maybe the tx hash so I can check it on the beryx explorer

**Comment by phantom-rabbit** [comment]
https://hyperspace.filfox.info/en/message/bafy2bzaceczbce7yvufibmn53rzcrpsp7wna5zjbq7ze5uvcn5prtynprpw34

**Comment by phantom-rabbit** [comment]
```
pragma solidity ^0.8.17;

import "@zondax/filecoin-solidity/contracts/v0.8/MinerAPI.sol";
import { MinerTypes } from "@zondax/filecoin-solidity/contracts/v0.8/types/MinerTypes.sol";

contract LoansContract {

    function getBeneficiary() external returns (MinerTypes.GetBeneficiaryReturn memory) {
        bytes memory addr = bytes("0x1111");
        MinerTypes.GetBeneficiaryReturn memory response = MinerAPI.getBeneficiary(addr);
        return response;
    }

}

```

**Comment by emmanuelm41** [comment]
You should pass there is the address (in bytes format) of a miner in the hyperspace network. You need to convert this address (https://hyperspace.filscan.io/address/miner?address=t01130) to bytes format, as it is in string format. You can use this package for that https://github.com/Zondax/filecoin-signing-tools/blob/cf8e6523f7226a1374c490ced2b02d739835ec60/signer-npm/js/src/index.ts#L40. 

This should be different. There you have the error. That is not a valid address.
`bytes memory addr = bytes("0x1111");`
