### ISSUE TITLE
Remove Structs with Single Types/Function Parameters

### ISSUE THREAD

**Issue by ZakAyesh** [Zondax/filecoin-solidity#142]
Many of the structs in the type libraries are structs of a single type such as:
```
  struct GetDealClientParams {
        uint64 id;
    }
```

This creates extra friction for developers in figuring out what the parameters for functions are doing because they have to double check in the types library. For example if I want to call this function:

`MarketAPI.getDealLabel(MarketTypes.GetDealLabelParams(dealId)).label;`

I have to got find out what types the GetDealLabelParams accept anyway. Where ever possible simple types with descriptive names should be used as function parameters.

:link: [zboto Link](https://app.clickup.com/t/86774gum7)

**Comment by ZenGround0** [comment]
Running into some friction here too and agree that it would be better and should be possible to keep the cbor compatible param types away from library users.

Another thing that will clean this up internally is to use a single QueryDealParam type for the very common getter input of a struct with a single field that is a deal id.  We use this in the builtin actors and it works well.

**Comment by emmanuelm41** [comment]
@ZakAyesh @ZenGround0 could you check the PR and tell me if that is enough? I think I changed what we were talking about.
