### ISSUE TITLE
Solidity Contract to Represent Init Actor

### ISSUE THREAD

**Issue by ZakAyesh** [Zondax/filecoin-solidity#149]
Currently if a Solidity dev wants to send FIL to a non Ethereum address in the FVM, they need to call Actor.call, from Actor.sol, and pass in the address hex"0001" along with all the other low level parameters. We could use a layer of abstraction for the Init Actor just like the MarketAPI.sol and MinerAPI.sol do for their respective actors. 

This will enable devs to send FIL to any address on Filecoin regardless if it's an Ethereum address or not. This contract should be able to take in any actorID from Filecoin, call the init actor and send FIL to the actorID.

:link: [zboto Link](https://app.clickup.com/t/86774verb)

**Comment by emmanuelm41** [comment]
@ZakAyesh we have the InitActor.sol contract on the repository. It has exported methods that Filecoin indicated. Is there any other method that we should add there? We should discuss it with Filecoin then. The library is [here](https://github.com/Zondax/filecoin-solidity/blob/master/contracts/v0.8/InitAPI.sol).

**Comment by emmanuelm41** [comment]
@ZakAyesh any comment here?
