### ISSUE TITLE
call actor ID precompile

### ISSUE THREAD

**Issue by ZenGround0** [Zondax/filecoin-solidity#164]
FVM has added a precompile to call an actor by its uint64 id rather than its filecoin address in bytes.  Support for this precompile would be very helpful as many builtin actors apis return actor ids rather than addresses.

:link: [zboto Link](https://app.clickup.com/t/86775r7y6)

**Comment by ZenGround0** [comment]
Here's a prototype from a fork I've been hacking on: https://github.com/ZenGround0/filecoin-solidity/blob/d77b3c87e6ad0a458f385d742a735bfe8d9c7b70/contracts/v0.8/utils/Actor.sol#L35

**Comment by emmanuelm41** [comment]
@ZenGround0 I have created a PR for that. Do you want to give me feedback?
