### ISSUE TITLE
Remix error using concat in getErrorCodeMsg

### ISSUE THREAD

**Issue by eshon** [Zondax/filecoin-solidity#167]
https://github.com/Zondax/filecoin-solidity/blob/36bb7854dc2242bf19c5e88c61f02ea8eb9f871b/contracts/v0.8/utils/Actor.sol#L76-L78

A hackathon developer (DÉX_ZËRØ) noticed [here in Discord](https://discord.com/channels/554623348622098432/822657841420435486/1067101064324726815) that these lines cause errors in Remix:

> "changed the code. Used Abi.encodePacked for low gas consumption. and now it compiled" 

<img width="866" alt="Screen Shot 2023-01-23 at 5 28 01 PM" src="https://user-images.githubusercontent.com/1017762/214094802-a40a6f44-72f6-440c-b29d-f266e296b3c0.png">

:link: [zboto Link](https://app.clickup.com/t/86777cpar)

**Comment by emmanuelm41** [comment]
Closed by #175
