### ISSUE TITLE
Always initialize structs and their internal fields

### ISSUE THREAD

**Issue by BlocksOnAChain** [Zondax/filecoin-solidity#196]
Throughout the API libraries, you’re using a pattern of declaring structs and passing them immediately to deserialize (and similar methods) without initializing them. Here’s an example from [MinerAPI.getOwner](https://github.com/Zondax/filecoin-solidity/blob/f21734e08c73443b11425e15a1292eb9013619c1/contracts/v0.8/MinerAPI.sol#L59-L60):

function getOwner(bytes memory target) internal returns (MinerTypes.GetOwnerReturn memory) {
  bytes memory raw_request = new bytes(0);

  bytes memory raw_response = Actor.call(MinerTypes.GetOwnerMethodNum, target, raw_request, Misc.NONE_CODEC, msg.value);

  bytes memory result = Actor.readRespData(raw_response);

  // HERE - response is passed to deserialize before being initialized
  MinerTypes.GetOwnerReturn memory response;
  response.deserialize(result);

  return response;
}
This pattern is dangerous because dynamic-sized fields in GetOwnerReturn are automatically assigned a “placeholder” memory pointer. To understand what’s happening under the hood, here’s the type definition for GetOwnerReturn ([ref](https://github.com/Zondax/filecoin-solidity/blob/f21734e08c73443b11425e15a1292eb9013619c1/contracts/v0.8/types/MinerTypes.sol#L45-L48)):

struct GetOwnerReturn {
  bytes owner;
  bytes proposed;
}
When you declare a variable of type GetOwnerReturn, the compiler allocates 2 words of memory to hold pointers to owner and proposed. This is because GetOwnerReturn has a known size at compile-time: it requires 1 word for each field.

However, the fields owner and proposed do NOT have a known size at compile time. When using this declaration syntax, solc doesn’t know how many bytes will eventually be in owner and proposed. In these cases, rather than allocating a word of memory to hold a zero-length array, solc uses a shortcut: owner and proposed are both set to the “zero slot” in memory, 0x60.

This means that, until something changes, owner and proposed point to the same array - a zero-length array located at 0x60. Looking at the corresponding [deserialize method](https://github.com/Zondax/filecoin-solidity/blob/f21734e08c73443b11425e15a1292eb9013619c1/contracts/v0.8/cbor/MinerCbor.sol#L54), I can see that owner is initialized in all cases. However, proposed may not be initialized, depending on the CBOR returned by the Miner actor.

The 0x60 reference is shared among all uninitialized dynamic-sized variables, so this can be especially dangerous if an API consumer attempts to write to proposed, or read from it after a similar reference is written to. As such, it’s standard practice to ensure that libraries never return references to 0x60.

Recommendation: familiarize yourself with Solidity’s memory layout. Here’s a starter reference:[docs.soliditylang.org/layout_in_memory](https://docs.soliditylang.org/en/v0.8.17/internals/layout_in_memory.html).

Additionaly, use a different pattern for declaring and using structs that avoids this issue. In general, avoid naked struct and bytes declarations like bytes memory myArray;. If it’s dynamic-sized or contains pointers to dynamic-sized values, it’s typically safer to start with an assignment like bytes memory myArray = new bytes(0);.

Here’s an example that avoids passing uninitialized memory pointers to the underlying library method:

> // Here, we're binding a library function to the `bytes` type, and it's assumed
> // that the underlying library function correctly initializes the struct and each
> // of its fields.
> //
> // This is better because we're not passing uninitialized pointers to the library,
> // To be safe, we need to make sure the library initializes everything.
> GetOwnerReturn memory response = result.deserializeGetOwnerReturn();

Here’s an example of the library method above, which works just like the current deserialize method, but ensures all fields are initialized before returning:

> function deserializeGetOwnerReturn(bytes memory rawResp) internal pure returns (GetOwnerReturn memory ret) {
>   uint byteIdx = 0;
>   uint len;
> 
>   (len, byteIdx) = rawResp.readFixedArray(byteIdx);
>   assert(len == 2);
> 
>   (ret.owner, byteIdx) = rawResp.readBytes(byteIdx);
> 
>   if (!rawResp.isNullNext(byteIdx)) {
>     (ret.proposed, byteIdx) = rawResp.readBytes(byteIdx);
>   } else {
>     ret.proposed = new bytes(0); // Explicitly allocate memory
>   }
> }

_This issue is create as a part of the the audit we did._

**Comment by emmanuelm41** [comment]
This issue is duplicated. It was covered here https://github.com/Zondax/filecoin-solidity/issues/177
