### ISSUE TITLE
Method number for `DataCap#Granularity` is changing in Carbonado.3

### ISSUE THREAD

**Issue by raulk** [Zondax/filecoin-solidity#221]
As you will notice, this frc42 hash was calculated over a string containing the `Exported` qualifier, in contrast to all other methods.

https://github.com/Zondax/filecoin-solidity/blob/fab54665a778b91be97d67154a970c8431e12c51/script/src/main.rs#L107

This is being corrected in the Carbonado.3 release, which will make it to Hyperspace on Feb 15th.

https://github.com/filecoin-project/builtin-actors/pull/1198#discussion_r1103130846

Please change this value in the library. We recognise that any contracts relying on this method will break, but it's a small cost to pay now for a desirable cleanup.

:link: [zboto Link](https://app.clickup.com/t/8677cwk7c)

**Comment by emmanuelm41** [comment]
@raulk I will change the value on the repo. However, that method is not covered on the libs, so there is nothing else we should change.
