### ISSUE TITLE
Add tooling to convert eth addresses and filecoin string addresses to byte formats

### ISSUE THREAD

**Issue by shrenujbansal** [Zondax/filecoin-solidity#227]
Certain APIs like addBalance, getBalance in MarketAPI.sol require byte formats of filecoin addresses as input
Could you please add some tooling to convert Eth addresses and filecoin string addresses to the input byte formats required by these APIs as those are the addresses most people deal with?
If this already exists, could you point me to it?

:link: [zboto Link](https://app.clickup.com/t/8677e3enj)

**Comment by rllola** [comment]
Hi!
We have a library that does the address conversion from string to bytes : https://github.com/Zondax/filecoin-signing-tools

**Comment by shrenujbansal** [comment]
@rllola Could you please point me to the specific place in the library where you have these tools?
