### ISSUE TITLE
Add lib function to convert ints/uints to BigInt and vice versa

### ISSUE THREAD

**Issue by shrenujbansal** [Zondax/filecoin-solidity#230]
It'd be very useful to add a library function to convert ints/uints to BigInt which is required by some structures in builtin actors

:link: [zboto Link](https://app.clickup.com/t/8677eec2w)

**Comment by emmanuelm41** [comment]
Hi @shrenujbansal! For that we found this [library](https://github.com/Zondax/solidity-BigNumber). As you can see, it is a fork. We just released the package on NPM for dev experience. I think it is enough for handling bigints from bulletin actors.

**Comment by shrenujbansal** [comment]
@emmanuelm41 I don't think we can use this library. It provides a struct BigNumber which is very different from the BigInt used by the builtin actors. This struct is defined and marshalled/unmarshalled in solidity here: https://github.com/Zondax/filecoin-solidity/blob/master/contracts/v0.8/cbor/BigIntCbor.sol#L22

We will be using this struct for fields within params/returns for the builtin actors and will need tooling for conversion for this

**Comment by emmanuelm41** [comment]
Builtin actors use a different structure, but when we serialize params we require BigInt (our own structure) as input type. Same when we deserialize return values. They are converted from builtin actors biting to BigInt (our own structure). That structure is very much compatible to the one defined on the library I shared before.

**Comment by emmanuelm41** [comment]
@shrenujbansal Am I missing something?
