### ISSUE TITLE
Error executing any method that uses "filecoin-solidity"

### ISSUE THREAD

**Issue by andborges** [Zondax/filecoin-solidity#232]
Hi,

Yesterday I was testing a smart contract using "filecoin-solidity" and everything went well.
But today I'm having this error all the time:

Error: transaction failed [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ]

Nothing changed at my side from yesterday, using pretty much the same deployed smart contract.
When I call another method on the same smart contract that do not use "filecoin-solidity", no errors.

Thanks.

:link: [zboto Link](https://app.clickup.com/t/8677ekwqe)

**Comment by emmanuelm41** [comment]
@andborges I think the issue is solved by the PR #234. Please, re open the issue if it still not working.
