### ISSUE TITLE
Makefile makes invalid assumptions

### ISSUE THREAD

**Issue by raulk** [Zondax/filecoin-solidity#236]
Checking out this repo and running `make` does not work because it assumes that the Solidity compiler is situated under `./bin/solc`, but it takes no actions to ensure that.

This repo should use the system compiler and perform feature detection to abort when it's not detected under `$PATH`.

:link: [zboto Link](https://app.clickup.com/t/8677eydr2)

**Comment by rllola** [comment]
It is because you should call `install_solc_linux` or `install_solc_macos` before.
