### ISSUE TITLE
Firm up external dependencies

### ISSUE THREAD

**Issue by raulk** [Zondax/filecoin-solidity#237]
## Problem

This library has four external dependencies -- all of them are self-contained utilities:

- CBOR: https://github.com/smartcontractkit/solidity-cborutils
- Buffer: https://github.com/ensdomains/buffer
- Strings: OpenZeppelin's String library
- BigNumber: forked from https://github.com/firoorg/solidity-BigNumber into https://github.com/Zondax/solidity-bignumber.

There are several problems with this approach.

1. It's not entirely clear how these dependencies are managed.
2. Some are npm dependencies.
3. There are Git submodules, but these are not locked to a specific commit -- this is **insecure**.
4. The Makefile picks them up from `node_modules`, but the Makefile doesn't run npm install.

## Proposal

Please be extra paranoid and vendor these dependencies into the repo (retaining attribution and conforming to licensing requirement -- all of them are permissive, so we're good.

:link: [zboto Link](https://app.clickup.com/t/8677eydxp)

**Comment by emmanuelm41** [comment]
@raulk what you suggest here is to copy the code from those libs and commit them in the repo itself. Is that what you meant?
