### ISSUE TITLE
Introduce an Address user-defined type

### ISSUE THREAD

**Issue by raulk** [Zondax/filecoin-solidity#241]
This library currently uses byte arrays for addresses in a number of places. This is unsafe and leads to very poor DX, as several users have manifested through confusion.

Recommendation: create a new [User Defined Value Type](https://docs.soliditylang.org/en/latest/types.html#user-defined-value-types) `FilecoinAddress`, along with a `Addressing` library with useful functions. For example:

- Create an f0 address from a `uint64` ActorID.
- Validate an address (should be used when sending data to built-in actors for better debuggability).

:link: [zboto Link](https://app.clickup.com/t/8677f4cpp)

**Comment by emmanuelm41** [comment]
Adding @snissn comments here (#269)
```
"FilecoinAddress idAddr = Addressing.fromActorID(actorID);
exist.

Also ensure there is a clear way to get to the filecoin address type from a string like "f2kmbjvz7vagl2z6pfrbjoggrkjofxspp7cqtw2zy"
```

**Comment by snissn** [comment]
To simplify this idea a bit, we want to create a FilecoinAddress type with three ways of populating that type.

We want support for creating a FilecoinAddress from 

1. uint64 actor id 
2. filecoin f2 address ie "f2kmbjvz7vagl2z6pfrbjoggrkjofxspp7cqtw2zy"
3. raw bytes

example psuedo code

```
uint64 actorID = 555555;
FilecoinAddress idAddr = Addressing.fromActorID(actorID);

or

string f_address =  "f2kmbjvz7vagl2z6pfrbjoggrkjofxspp7cqtw2zy"
FilecoinAddress fAddr = Addressing.fromFilecoinAddress(f_address);

or

bytes constant raw_bytes_example = hex"0000000000000000000000000000000000000000000000000000000000000000"; 
FilecoinAddress rawAddr = Addressing.fromBytes(raw_bytes_example);

```

**Comment by emmanuelm41** [comment]
For the JS tooling, we have this one 
https://www.npmjs.com/package/@zondax/izari-tools
