### ISSUE TITLE
Run static analysis tools

### ISSUE THREAD

**Issue by ainhoa-a** [Zondax/filecoin-solidity#251]
similar to  https://github.com/ConsenSys/mythril and https://github.com/crytic/rattle

:link: [zboto Link](https://app.clickup.com/t/8677ffdjx)

**Comment by BlocksOnAChain** [comment]
@emmanuelm41  - Hey, can you share some findings from running the static analysis tests? Did everything look ok after the run and what results did we get?

**Comment by BlocksOnAChain** [comment]
there is also a bunch of others we can try, if you have the time: https://consensys.net/diligence/tools/

**Comment by emmanuelm41** [comment]
@BlocksOnAChain this is the latest check ran 
https://github.com/Zondax/filecoin-solidity/actions/runs/4251828342

The other tools you mentioned there are not actually tools that we can use. Some of them are VS plugins, others are paid ones.
