### ISSUE TITLE
Unit test FRC0042 method numbers

### ISSUE THREAD

**Issue by Stebalien** [Zondax/filecoin-solidity#262]
Right now, they're hard-coded but it's easy to accidentally get then wrong and/or change them. There should be unit tests for each method number that:

1. Generate the method number from the method name according to FRC0042.
2. Check that the hard-coded method number matches.

:link: [zboto Link](https://app.clickup.com/t/8677fmw1y)

**Comment by snissn** [comment]
@maciejwitowski this one is yours - but I don't have assignment privileges

**Comment by rllola** [comment]
@Stebalien Do you have a unique source of truth that we can use for the method number ?

**Comment by Stebalien** [comment]
No, they have to be computed according to https://github.com/filecoin-project/FIPs/blob/master/FRCs/frc-0042.md#method-number-computation.

The ask is to ensure that the hard-coded frc0042 numbers match the expected numbers based on the method names (it's easy to flub constants like this).

**Comment by rllola** [comment]
We generated them using this script https://github.com/Zondax/filecoin-solidity/blob/master/script/src/main.rs#L4

But we would like to have a source from filecoin.

**Comment by snissn** [comment]
I believe this is relevant: https://github.com/filecoin-project/builtin-actors/blob/master/actors/market/src/lib.rs#L81

you can grep for `frc42_dispatch::method_hash` in the builtin-actors repo too

**Comment by snissn** [comment]
@rllola 

I believe this is relevant: https://github.com/filecoin-project/builtin-actors/blob/master/actors/market/src/lib.rs#L81

you can grep for `frc42_dispatch::method_hash` in the builtin-actors repo too
