### ISSUE TITLE
SendAPI.sol - support sending to filecoin address

### ISSUE THREAD

**Issue by snissn** [Zondax/filecoin-solidity#268]
Support sending filecoin to an account by specifying the account address.

It's very possible to need to send value to an address which does not yet have a filecoin account id 

:link: [zboto Link](https://app.clickup.com/t/8677fn44y)

**Comment by emmanuelm41** [comment]
This was discussed internally and we concluded that the actor id can be resolved using the `resolve_address` precompile if needed. Is there some corner case where an address has no actor id?

**Comment by raulk** [comment]
Yes, there is a corner case, concretely (1) from this list:

1. Transferring value to an f1/f3 address. In this case the address may or may not exist (i.e. no ID). There's a high likelihood that the address will be user-input and incoming as a parameter. In that case, the library should suggest users to use the SendAPI: https://github.com/Zondax/filecoin-solidity/blob/master/contracts/v0.8/SendAPI.sol#L29
2. Calling the Miner actor: will use an ID in 99% of cases, and the Solidity interface can revolve around IDs only. Can drop support for the address variant without noticeable developer experience loss. Let's do that.
3. Calling the Account actor: this is a bit of a special case. Would also retain only the ID variant and document that addresses can be converted through the resolve_address precompile.

**Comment by raulk** [comment]
So I believe this issue intends to create good DX for (1).

**Comment by emmanuelm41** [comment]
@raulk but for (1) what should we do then? leave SendAPI with bytes as parameter? We could create two different ones with different parameters: id or address

**Comment by snissn** [comment]
confirming the intention was to create good DX for (1) thanks 😃
