### ISSUE TITLE
Filecoin address helper functions

### ISSUE THREAD

**Issue by snissn** [Zondax/filecoin-solidity#269]
mentioned in https://github.com/Zondax/filecoin-solidity/issues/242

ensure methods like 
FilecoinAddress idAddr = Addressing.fromActorID(actorID);
exist. 

Also ensure there is a clear way to get to the filecoin address type from a string like "f2kmbjvz7vagl2z6pfrbjoggrkjofxspp7cqtw2zy" 

:link: [zboto Link](https://app.clickup.com/t/8677fn5kc)

**Comment by emmanuelm41** [comment]
Resetead from #241
