### ISSUE TITLE
PowerAPI.sol 

### ISSUE THREAD

**Issue by snissn** [Zondax/filecoin-solidity#270]
```        
require(address(this).balance >= value, "not enough balance");
```
https://github.com/Zondax/filecoin-solidity/blob/master/contracts/v0.8/PowerAPI.sol#L40

We should consider the other places value is sent through this library and add this assertion in those places, or move this assertion into callByAddress in a refactor

:link: [zboto Link](https://app.clickup.com/t/8677fn6q3)

**Comment by emmanuelm41** [comment]
Only two methods actually can send funds to the native actor they are calling: addBalance (market) and createMiner (power). That is why this check is only attached to this specific methods. It is set in both places. It would be better to move them to `callByAddress` as the balance will never be lower than 0.
