### ISSUE TITLE
remove first byte check in callByAddress

### ISSUE THREAD

**Issue by snissn** [Zondax/filecoin-solidity#276]
https://github.com/Zondax/filecoin-solidity/blob/master/contracts/v0.8/utils/Actor.sol#L53

remove 

```
        require(
            actor_address[0] == 0x00 || actor_address[0] == 0x01 || actor_address[0] == 0x02 || actor_address[0] == 0x03 || actor_address[0] == 0x04,
            "actor_address address should be bytes format"
        );
```

As this puts an unwanted limitation on future filecoin actor addresses that are acceptable

Change this to a check that actor_address is at least one character/byte long

cc @Stebalien to confirm this is the intended change

:link: [zboto Link](https://app.clickup.com/t/8677fnajg)

**Comment by emmanuelm41** [comment]
@snissn this check was added as part of the auditor recommendations. I understand the future filecoin actor addresses issue, but we need to fail early someway if the user is not sending an address in bytes format (like using string format). We could do something like `actor_address[0] < 10`?

**Comment by snissn** [comment]
thank you! This change to `require(actor_address.length > 1, "invalid actor_address");` looks good!
