### ISSUE TITLE
writeCid and argument count

### ISSUE THREAD

**Issue by snissn** [Zondax/filecoin-solidity#279]
It looks like 
```
cbor/FilecoinCbor.sol:    function writeCid(CBOR.CBORBuffer memory buf, bytes memory value) internal pure {
```
has two arguments, and when it is used in cbor/InitCbor.sol and cbor/MarketCbor.sol it is called with only one argument:

```
cbor/InitCbor.sol:        buf.writeCid(params.code_cid);
cbor/InitCbor.sol:        buf.writeCid(params.code_cid);
cbor/MarketCbor.sol:            buf.writeCid(params.deals[i].proposal.piece_cid);
```

:link: [zboto Link](https://app.clickup.com/t/8677fnc04)

**Comment by emmanuelm41** [comment]
This is because the first argument is the `buf` variable itself. It is like in GoLang.

**Comment by snissn** [comment]
thank you!
