### ISSUE TITLE
./utils/Actor.sol error handling

### ISSUE THREAD

**Issue by snissn** [Zondax/filecoin-solidity#280]
Error handling is done via

`require(success == true, CALL_ERROR_MESSAGE);` where CALL_ERROR_MESSAGE is a constant. This swallows any potential error messages that were propogated from the delegated contract call. I suggest changing the require check to something like

`require(success == true, data);` to ensure the error message gets bubbled up properly.

Note may be preferable to change success == true to just checking the bool success 

:link: [zboto Link](https://app.clickup.com/t/8677fndvp)

**Comment by emmanuelm41** [comment]
@snissn when success is `false`, do we have an error message on `data`? If that is the case, we will apply the change as it will be more insightful for devs!

**Comment by raulk** [comment]
@snissn what do you think about using custom error types here? https://blog.soliditylang.org/2021/04/21/custom-errors/
They are not yet supported in `require`, but it sounds like the benefits may be worth it anyway:

> Currently, there is no convenient way to catch errors in Solidity, but this is planned, and progress can be tracked in issue [#11278](https://github.com/ethereum/solidity/issues/11278). Also, require(condition, "error message") should be translated to if (!condition) revert CustomError().

**Comment by raulk** [comment]
I personally feel uneasy about dumping unwrapped bytes on require.

**Comment by snissn** [comment]
@emmanuelm41 
Here's an example of propagating errors in solidity https://gist.github.com/snissn/9553d86da644d63749a062d7dfc11aa8 (shout out to chat gpt for helping me write this contract yesterday 😄  )  remix.ethereum.org shows me the error here when i run it:
<img width="637" alt="image" src="https://user-images.githubusercontent.com/1981537/220696476-8ae98201-d380-44eb-9c92-3b77d8866cb6.png">


@raulk defintely defer to you and others on the content of the error messages and how to handle them.  Big picture my thinking is if there's an error on the fvm side, it would be nice as a user of the solidity filecoin library to see that error if they're relevant and actionable.

**Comment by emmanuelm41** [comment]
@snissn the question here is what actors return when the call is not successful. I see we can propagate them, but I am not sure what actors actually return

**Comment by snissn** [comment]
From a conversation with @stebalien there is not really an error code that the FVM propogats to the EVM that is worth exposing to the user. 

That said we can add [custom errors](https://blog.openzeppelin.com/defining-industry-standards-for-custom-error-messages-to-improve-the-web3-developer-experience/) to our contract to improve usability of the api

This is a new-ish solidity feature! ([April 2021](https://blog.soliditylang.org/2021/04/21/solidity-0.8.4-release-announcement/))
