### ISSUE TITLE
CBOR deserialize checks and error handling

### ISSUE THREAD

**Issue by snissn** [Zondax/filecoin-solidity#283]
I'm personally unclear if there's error checking that needs to be added to CBOR deserialize methods. If the response is an invalid cbor object, does the code know and propagate that? Should it? 

sibling issue with #274

:link: [zboto Link](https://app.clickup.com/t/8677fnezy)

**Comment by emmanuelm41** [comment]
When deserializing responses from actors, we should use assert as it should never fail. If something fails, it means there is a bug. That is why there is no error propagation (like require or revert). We have rusts tests as integration tests where serialization and deserialization is tested.
