### ISSUE TITLE
More instances of bytes vs id addresses in inputs and Structs

### ISSUE THREAD

**Issue by snissn** [Zondax/filecoin-solidity#287]
#263 for background.

Many of the types / structs being used specify the type of filecoin address variables in bytes. For example:
in [DataCapAPI.burnFrom](https://github.com/Zondax/filecoin-solidity/blob/master/contracts/v0.8/DataCapAPI.sol#L158)
DataCapAPI.sol calls by address into DataCapTypes.ActorID -> [DataCapTypes.BurnFromMethodNum](https://github.com/Zondax/filecoin-solidity/blob/master/contracts/v0.8/types/DataCapTypes.sol#L120) with params:

```
   struct BurnFromParams {
        bytes owner;
        BigInt amount;
    }
```

so a solidity user will need to construct bytes owner. Can this be moved to a filecoin id?  

Below is a non exhaustive list of such parameters that can be changed:

MinerAPI.sol
- [ ] bytes memory addr

DataCapAPI.sol
- [ ] balance(bytes memory addr) internal

MarketAPI.sol
- [ ] addBalance(bytes memory provider_or_client 
- [ ] getBalance(bytes memory addr)

Precompiles.sol

- [ ] resolveAddress(bytes memory addr)
- [ ] resolveEthAddress(bytes memory addr)
- [ ] lookupDelegatedAddress returns (bytes memory)

SendAPI.sol

- [ ] send(bytes memory toAddress

types/AccountTypes.sol

- [ ] All instances of operator and owner should be filecoin addresses

types/InitTypes.sol

- [ ] bytes code_cid should be 20 bytes

- [ ] Filecoin addresses: id_address, robust_address, subaddress

types/MarketTypes.sol

- [ ] bytes piece_cid, bytes provider_or_client, bytes provider, bytes client,

types/MinerTypes.sol

- [ ] bytes owner; bytes proposed; bytes addr, bytes new_worker, bytes amount_requested, bytes amount_withdrawn, bytes new_beneficiary

types/PowerTypes.sol

- [ ] bytes owner, bytes worker, bytes peer, bytes id_address, bytes[] multiaddrs, bytes robust_address, 

types/VerifRegTypes.sol

- [ ] bytes addr

:link: [zboto Link](https://app.clickup.com/t/8677fnm3w)

**Comment by emmanuelm41** [comment]
@snissn this could be something interesting to do if we first create some kind of utility functions to handle filecoin addresses on solidity (check, convert from string to bytes, from bytes to string, etc). Until we don't have something like that, it will be impossible to do it.

**Comment by emmanuelm41** [comment]
Depends on #241
