### ISSUE TITLE
Using staticcall for builtIn actors readonly APIs

### ISSUE THREAD

**Issue by longfeiWan9** [Zondax/filecoin-solidity#289]
This concern is raised in [Slack](https://filecoinproject.slack.com/archives/C04AT6ZKJC9/p1677047700338289).

Currently, Filecoin.solidity invokes builtIn Actor using DelegateCall() for both readOnly APIs and APIs which might change the state of the blockchain. For readOnly APIs, solidity devs might want to write their solidity functions as view to simple read without sending transactions. But they cannot because it is not allowed to declare functions as view if DelegateCall is used to read data on-chain. 

So we would suggest trying to use staticcall to invoke readOnly APIs from builtIn actors and provide those API as view functions. 

:link: [zboto Link](https://app.clickup.com/t/8677fq65q)

**Comment by rllola** [comment]
The precompiles only allow DelegateCall.

https://github.com/filecoin-project/builtin-actors/blob/master/actors/evm/src/interpreter/precompiles/fvm.rs#L130

**Comment by Stebalien** [comment]
However, we _can_ set the read-only flag in these cases, just to be safe.

**Comment by emmanuelm41** [comment]
Read only flags for methods that don't change the state have been set. So I think this issue can be closed, as we are doing the best we can (use the read only flag)
