### ISSUE TITLE
failing ci test:  SimpleCoin: end-to-end tests

### ISSUE THREAD

**Issue by snissn** [Zondax/filecoin-solidity#306]
latest commit #8a7d7bd9d854ed813b28b522af34e17924d74a23

triggers this ci error https://github.com/Zondax/filecoin-solidity/actions/runs/4263884359/jobs/7421198411#logs

:link: [zboto Link](https://app.clickup.com/t/8677gjhet)

**Comment by emmanuelm41** [comment]
Nothing to worry about. When there is more that one running at the same time, two txs are in the mempool at the same time. That is why it fails. If you re run that job, it will work
