### ISSUE TITLE
Prefer `bytes.concat` over `abi.encodePacked` for concatenation

### ISSUE THREAD

**Issue by Stebalien** [Zondax/filecoin-solidity#328]
See https://github.com/ethereum/solidity/issues/10903.

:link: [zboto Link](https://app.clickup.com/t/8677ht008)

**Comment by emmanuelm41** [comment]
@Stebalien there is only one place where we could actually replace this. Other places are not concatenating bytes only. 
https://github.com/Zondax/filecoin-solidity/blob/d9fded44f38baa403dbf4981a38b062555355da5/contracts/v0.8/utils/FilAddresses.sol#L44

**Comment by emmanuelm41** [comment]
Should we change only that place?

**Comment by Stebalien** [comment]
Ah, because the other places are using non bytes types. I see.

Nah, makes sense. Sorry for the noise.

**Comment by emmanuelm41** [comment]
@Stebalien np at all! Thanks for the feedback
