### ISSUE TITLE
Q: any support for sending assets to f1/f3 addresses?

### ISSUE THREAD

**Issue by Fatman13** [Zondax/filecoin-solidity#330]
Hello, team, I was looking at https://github.com/Zondax/filecoin-solidity/blob/master/contracts/v0.8/utils/FilAddresses.sol and wondering if there is any support on sending assets like erc-20 tokens to f1/f3 addresses in a FEVM sol contract? 

:link: [zboto Link](https://app.clickup.com/t/8677j75e5)

**Comment by raulk** [comment]
Yes: https://github.com/Zondax/filecoin-solidity/blob/master/contracts/v0.8/SendAPI.sol#L28
