### ISSUE TITLE
Delegatecall used without checking target address exists

### ISSUE THREAD

**Issue by ainhoa-a** [Zondax/filecoin-solidity#340]
Please verify that CALL_ACTOR_ADDRESS or CALL_ACTOR_ID exist before applying delegatecall.

When a non-existing target address is passed to delegatecall it will return true even though the call was not performed.

The low-level functions call, delegatecall and staticcall return true as their first return value if the account called is non-existent, as part of the design of the EVM. Account existence must be checked prior to calling if needed.

- [Solidity documentation - Expressions and Control Structures](https://docs.soliditylang.org/en/v0.8.17/control-structures.html?highlight=delegatecall#error-handling-assert-require-revert-and-exceptions)

Delegatecalls are used in utils/Actor.sol to perform callByAddress and callByID to invoke actors:

        (bool success, bytes memory data) = address(CALL_ACTOR_ADDRESS).delegatecall(
            abi.encode(uint64(method_num), value, static_call ? READ_ONLY_FLAG : DEFAULT_FLAG, codec, raw_request, actor_address)
        );
- [utils/Actor.sol](https://github.com/Zondax/filecoin-solidity/blob/v3.0.0-beta.1/contracts/v0.8/utils/Actor.sol#L92-L94)

        (bool success, bytes memory data) = address(CALL_ACTOR_ID).delegatecall(
            abi.encode(uint64(method_num), value, static_call ? READ_ONLY_FLAG : DEFAULT_FLAG, codec, raw_request, target)
        );
- [utils/Actor.sol](https://github.com/Zondax/filecoin-solidity/blob/v3.0.0-beta.1/contracts/v0.8/utils/Actor.sol#L123-L125)

If CALL_ACTOR_ADDRESS or CALL_ACTOR_ID does not exist it will cause delegatecall to succeed.
As a result of this, the API functions that does not expect any data to be returned will still succeed!

:link: [zboto Link](https://app.clickup.com/t/85zrq2vv8)

**Comment by Stebalien** [comment]
The FVM guarantees that this address will exist. Checking if it exists before calling is unnecessary and a waste of gas.

**Comment by emmanuelm41** [comment]
@Stebalien I know! But this was raised by the auditors!

**Comment by Stebalien** [comment]
Feel free to reject suggestions by the auditors. They're just that, notices and suggestions. In fact, they can even be dangerous (see https://github.com/Zondax/filecoin-solidity/issues/345).

**Comment by Stebalien** [comment]
Basically, auditors look for parts of your code that _may_ be dangerous and/or may not behave as you intend. However, at the end of the day, you likely know _much_ more about Filecoin, your code-base, and your users/product.
