### ISSUE TITLE
How to get raw bytes format of filecoin address?

### ISSUE THREAD

**Issue by Sunnight-wj** [Zondax/filecoin-solidity#350]
i want to test send function by filAddress using SendAPI, but i don't kown how to convert human readable format to raw bytes format of filecoin address.is there any js or ts library to do this?

:link: [zboto Link](https://app.clickup.com/t/85zrqhp1u)

**Comment by emmanuelm41** [comment]
@Sunnight-wj yes, we have this library for that, and much more. You can check the readme! 

https://github.com/Zondax/izari-tools#addresses

**Comment by emmanuelm41** [comment]
Please, feel free to ask anything else, or close the issue if the answer is enough!

**Comment by Sunnight-wj** [comment]
thanks, it's enough! i will close this issue.

**Comment by emmanuelm41** [comment]
@Sunnight-wj sorry for the inconvenience. It is published here 
https://github.com/Zondax/beryx-tools-filecoin/releases/tag/v0.1.0-rc1
