### ISSUE TITLE
Consider using staticcall to call read-only built-in actor getters

### ISSUE THREAD

**Issue by raulk** [Zondax/filecoin-solidity#362]
This library uses delegatecall to call the precompile in all occasions, even if the built-in actor method is a getter. This prevents contract using this library from declaring `view` functions that invoke built-in actor getters, even if those functions are, in practice, read-only functions. 

:link: [zboto Link](https://app.clickup.com/t/8677u5y8f)

**Comment by rllola** [comment]
Using `staticcall` is not allowed by filecoin actor.
See
https://github.com/filecoin-project/builtin-actors/blob/master/actors/evm/src/interpreter/precompiles/fvm.rs#L130-L132

**Comment by emmanuelm41** [comment]
@raulk take a look at this
https://github.com/Zondax/filecoin-solidity/blob/b58b5c28caad12f54b7ca203e52b4383cc0f7772/contracts/v0.8/utils/Actor.sol#L85-L91
